stepshop/authapp/urls.py
from django.urls import path
from .views import login, logout, register, edit

app_name = 'authapp'


urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
]

stepshop/basketapp/urls.py
from django.urls import path

from basketapp.views import basket, basket_add, basket_remove
app_name = 'basketapp'

urlpatterns = [
    path('', basket, name='view'),
    path('add/<int:pk>/', basket_add, name='add'),
    path('remove/<int:pk>/', basket_remove, name='remove'),
]

stepshop/stepshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import index, contacts, about


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),
    path('about/', about, name='about'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stepshop/basketapp/models.py
from django.db import models

from stepshop import settings

from mainapp.models import Product


class Basket(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='basket'
    )

    quantity = models.PositiveIntegerField(
        verbose_name='quantity',
        default=0
    )

    add_datetime = models.DateTimeField(
        verbose_name='time',
        auto_now_add=True,
    )

    class Meta:
        verbose_name = 'basket'
        verbose_name_plural = 'basket'

stepshop/basketapp/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404

from basketapp.models import Basket
from mainapp.models import Product

from stepshop.views import get_basket


def basket(request):
    if request.user.is_authenticated:
        user_basket = Basket.objects.filter(user=request.user)
        context = {
            'basket': user_basket
        }
        return render(request, 'basketapp/basket.html', context)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def basket_add(request, pk):
    pk -= 1
    product = get_object_or_404(Product, pk=pk)

    basket = Basket.objects.filter(user=request.user, product=product).first()

    if not basket:
        basket = Basket(user=request.user, product=product)

    basket.quantity += 1
    basket.save()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def basket_remove(request, pk):
    pk -= 1

    product = get_object_or_404(Product, pk=pk)

    basket = Basket.objects.filter(user=request.user, product=product).first()

    if not basket:
        basket = Basket(user=request.user, product=product)

    basket.quantity -= 1
    basket.save()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

stepshop/basketapp/templates/basketapp/basket.html
{% extends 'stepshop/base.html' %}
{% load static %}

{% block content %}

{% if user.is_authenticated %}
<div class="container" style="margin-top:130px;">
    <div class="row">
        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Продукт</th>
                <th scope="col">Количество</th>
                <th scope="col">Добавить</th>
                <th scope="col">Убавить</th>
            </tr>
            </thead>
            <tbody>
            {% for item in basket %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ item.product }}</td>
                <td>{{ item.quantity }}</td>
                <td>
                    <a href="{% url 'basketapp:add' item.id %}">
                        <button class="btn btn-dark mx-1">+</button>
                    </a>
                </td>
                <td>
                   <a href="{% url 'basketapp:remove' item.id %}">

                    <button class="btn btn-dark mx-1">-</button>
                   </a>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endif %}

{% endblock %}