stepshop/authapp/urls.py
from django.urls import path
from .views import login, logout, register, edit

app_name = 'authapp'


urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
]

stepshop/stepshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import index, contacts, about


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),
    path('about/', about, name='about'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stepshop/stepshop/views.py
from django.shortcuts import render
from mainapp.models import Product

from basketapp.models import Basket


def get_basket(request):
    basket = []
    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)
    return basket


def index(request):
    title = 'магазин'

    basket = get_basket(request)

    products = Product.objects.all()  # [:4]

    context = {
        'title': title,
        'products': products,
        'basket': basket,
    }

    return render(request, 'stepshop/index.html', context=context)


def contacts(request):
    title = 'contacts'

    basket = get_basket(request)

    context = {
        'title': title,
        'basket': basket
    }
    return render(request, 'stepshop/contact.html', context=context)


def about(request):
    title = 'about'

    basket = get_basket(request)

    context = {
        'title': title,
        'basket': basket
    }

    return render(request, 'stepshop/about.html', context=context)

stepshop/stepshop/templates/stepshop/includes/inc_main_menu.html
{% load static %}

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
  <div class="container">
    <a class="navbar-brand" href="#"><img src="{% static 'stepshop/images/header-logo.png' %}" alt=""></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item
                    {% if request.resolver_match.route == '' %}active{% endif %}
                  ">
          <a class="nav-link" href="{% url 'index' %}">Home
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item
                    {% if request.resolver_match.route == 'products/' %}active{% endif %}
                  ">
          <a class="nav-link" href="{% url 'products:index' %}">Products</a>
        </li>
        <li class="nav-item
                    {% if request.resolver_match.route == 'about/' %}active{% endif %}
                  ">
          <a class="nav-link" href="{% url 'about' %}">About&nbsp;Us</a>
        </li>
        <li class="nav-item
                    {% if request.resolver_match.route == 'contacts/' %}active{% endif %}
                  ">
          <a class="nav-link" href="{% url 'contacts' %}">Contact&nbsp;Us</a>
        </li>

        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'auth:edit' %}">
            {{ user.first_name|default:user.username }}
          </a>
        </li>
        {% endif %}

        <li class="nav-item">
          {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'auth:logout' %}">выйти</a>
          {% else %}
            <a class="nav-link" href="{% url 'auth:login' %}">войти</a>
          {% endif %}
        </li>

      </ul>
    </div>
  </div>
</nav>