stepshop/authapp/urls.py
from django.urls import path
from .views import login, logout, register, edit

app_name = 'authapp'


urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
]

stepshop/basketapp/urls.py
from django.urls import path

from basketapp.views import basket, basket_add, basket_remove
app_name = 'basketapp'

urlpatterns = [
    path('', basket, name='view'),
    path('add/<int:pk>/', basket_add, name='add'),
    path('remove/<int:pk>/', basket_remove, name='remove'),
]

stepshop/mainapp/urls.py
from django.urls import path

from .views import products, product

app_name = 'products'

urlpatterns = [
    path('', products, name='index'),
    path('category/<int:pk>/', products, name='category'),
    path('product/<int:pk>/', product, name='product'),

]

stepshop/stepshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import index, contacts, about


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),
    path('about/', about, name='about'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stepshop/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(
        verbose_name='name',
        max_length=64,
        unique=True,
    )
    description = models.TextField(
        verbose_name='description',
        blank=True,
    )

    def __str__(self):
        return self.name or f'Category with id - {self.pk}'

    class Meta:
        verbose_name = 'category',
        verbose_name_plural = 'categories'


class Product(models.Model):
    category = models.ForeignKey(
        ProductCategory,
        on_delete=models.CASCADE,
        verbose_name='category',
    )

    name = models.CharField(
        verbose_name='product name',
        max_length=228,
    )

    image = models.ImageField(
        upload_to='product_images',
        blank='True',
        verbose_name='image'
    )

    short_desc = models.CharField(
        verbose_name='short description',
        max_length=228,
    )

    description = models.TextField(
        verbose_name='description',
        blank=True,
    )

    price = models.DecimalField(
        verbose_name='price',
        max_digits=8,
        decimal_places=2,
        default=0,
    )

    quantity = models.PositiveIntegerField(
        verbose_name='storage_quantity',
        default=0,
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
    )

    updated_at = models.DateTimeField(
        auto_now=True,
    )

    def __str__(self):
        return self.name or f'Product with id - {self.pk}'

    class Meta:
        verbose_name = 'product',
        verbose_name_plural = 'products',

stepshop/mainapp/views.py
from django.shortcuts import render, get_object_or_404

from mainapp.models import ProductCategory, Product

from basketapp.models import Basket

from stepshop.views import get_basket


def products(request, pk=0):
    title = 'продукты | каталог'

    links_menu = ProductCategory.objects.all()
    products_all = Product.objects.all().order_by('price')


    context = {
        'title': title,
        'links_menu': links_menu,
        'products_all': products_all,
        'basket': get_basket()

    }

    # if pk is not None:
    if pk == 0:
        products_all = Product.objects.all().order_by('price')
        category = {'name': 'все', 'pk': 0}
    else:
        category = get_object_or_404(ProductCategory, pk=pk)
        products_all = Product.objects.filter(category__pk=pk).order_by('price')

    context['category'] = category
    context['products_all'] = products_all

    return render(request=request, template_name='mainapp/products.html', context=context)


def product(request, pk):
    title = 'продукт'

    links_menu = ProductCategory.objects.all()
    current_product = get_object_or_404(Product, pk=pk)

    context = {
        'title': title,
        'links_menu': links_menu,
        'current_product': current_product,
        'basket': get_basket(request)
    }

    return render(request=request, template_name='mainapp/product.html', context=context)

stepshop/mainapp/templates/mainapp/product.html
{% extends 'stepshop/base.html' %}
{% load static %}

{% block content %}
    <!-- Page Content -->
    <!-- Single Starts Here -->
    <div class="single-product">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <div class="line-dec"></div>
              <h1>Single Product</h1>
            </div>
          </div>
          <div class="col-md-6">
            <div class="product-slider">
              <div id="slider" class="flexslider">
                <ul class="slides">
                  <li>
                    <img src="assets/images/big-01.jpg" />
                  </li>
                  <li>
                    <img src="assets/images/big-02.jpg" />
                  </li>
                  <li>
                    <img src="assets/images/big-03.jpg" />
                  </li>
                  <li>
                    <img src="assets/images/big-04.jpg" />
                  </li>
                  <!-- items mirrored twice, total of 12 -->
                </ul>
              </div>
              <div id="carousel" class="flexslider">
                <ul class="slides">
                  <li>
                    <img src="assets/images/thumb-01.jpg" />
                  </li>
                  <li>
                    <img src="assets/images/thumb-02.jpg" />
                  </li>
                  <li>
                    <img src="assets/images/thumb-03.jpg" />
                  </li>
                  <li>
                    <img src="assets/images/thumb-04.jpg" />
                  </li>
                  <!-- items mirrored twice, total of 12 -->
                </ul>
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="right-content">
              <h4>Single Product Name</h4>
              <h6>$55.00</h6>
              <p>Proin commodo, diam a ultricies sagittis, erat odio rhoncus metus, eu feugiat lorem lacus aliquet arcu. Curabitur in gravida nisi, non placerat nibh. Praesent sit amet diam ultrices, commodo turpis id, dignissim leo. Suspendisse mauris massa, porttitor non fermentum vel, ullamcorper scelerisque velit. </p>
              <span>7 left on stock</span>
              <div class="main-button">
                <a href="{% url 'basket:add' current_product.pk %}">ORDER</a>
              </div>
              <div class="down-content">
                <div class="categories">
                  <h6>Category: <span><a href="#">Pants</a>,<a href="#">Women</a>,<a href="#">Lifestyle</a></span></h6>
                </div>
                <div class="share">
                  <h6>Share: <span><a href="#"><i class="fa fa-facebook"></i></a><a href="#"><i class="fa fa-linkedin"></i></a><a href="#"><i class="fa fa-twitter"></i></a></span></h6>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Single Page Ends Here -->


    <!-- Similar Starts Here -->
    <div class="featured-items">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <div class="line-dec"></div>
              <h1>You May Also Like</h1>
            </div>
          </div>
          <div class="col-md-12">
            <div class="owl-carousel owl-theme">
              <a href="single-product.html">
                <div class="featured-item">
                  <img src="assets/images/item-01.jpg" alt="Item 1">
                  <h4>Proin vel ligula</h4>
                  <h6>$15.00</h6>
                </div>
              </a>
              <a href="single-product.html">
                <div class="featured-item">
                  <img src="assets/images/item-02.jpg" alt="Item 2">
                  <h4>Erat odio rhoncus</h4>
                  <h6>$25.00</h6>
                </div>
              </a>
              <a href="single-product.html">
                <div class="featured-item">
                  <img src="assets/images/item-03.jpg" alt="Item 3">
                  <h4>Integer vel turpis</h4>
                  <h6>$35.00</h6>
                </div>
              </a>
              <a href="single-product.html">
                <div class="featured-item">
                  <img src="assets/images/item-04.jpg" alt="Item 4">
                  <h4>Sed purus quam</h4>
                  <h6>$45.00</h6>
                </div>
              </a>
              <a href="single-product.html">
                <div class="featured-item">
                  <img src="assets/images/item-05.jpg" alt="Item 5">
                  <h4>Morbi aliquet</h4>
                  <h6>$55.00</h6>
                </div>
              </a>
              <a href="single-product.html">
                <div class="featured-item">
                  <img src="assets/images/item-06.jpg" alt="Item 6">
                  <h4>Urna ac diam</h4>
                  <h6>$65.00</h6>
                </div>
              </a>
              <a href="single-product.html">
                <div class="featured-item">
                  <img src="assets/images/item-04.jpg" alt="Item 7">
                  <h4>Proin eget imperdiet</h4>
                  <h6>$75.00</h6>
                </div>
              </a>
              <a href="single-product.html">
                <div class="featured-item">
                  <img src="assets/images/item-05.jpg" alt="Item 8">
                  <h4>Nullam risus nisl</h4>
                  <h6>$85.00</h6>
                </div>
              </a>
              <a href="single-product.html">
                <div class="featured-item">
                  <img src="assets/images/item-06.jpg" alt="Item 9">
                  <h4>Cras tempus</h4>
                  <h6>$95.00</h6>
                </div>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Similar Ends Here -->
{% endblock %}

stepshop/mainapp/templates/mainapp/products.html
{% extends 'stepshop/base.html' %}
{% load static %}

{% block content %}
  <!-- Page Content -->
    <!-- Items Starts Here -->
    <div class="featured-page">
      <div class="container">
            {% include 'mainapp/includes/inc_category_menu.html'%}
      </div>
    </div>

    <div class="featured container no-gutter">

        <div class="row posts">
            {% for product in products_all %}
            <div id="{{product.pk}}" class="item new col-md-4">
              <a href="{% url 'products:product' product.pk %}">
                <div class="featured-item">
                  <img src="/media/{{product.image}}" alt="{{product.short_desc}}">
                  <h4>{{product.name}}</h4>
                  <h6>${{product.price}}</h6>
                </div>
              </a>
            </div>
            {% endfor %}
        </div>
    </div>

    <div class="page-navigation">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <ul>
              <li class="current-page"><a href="#">1</a></li>
              <li><a href="#">2</a></li>
              <li><a href="#">3</a></li>
              <li><a href="#"><i class="fa fa-angle-right"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <!-- Featred Page Ends Here -->
{% endblock %}

{% block scripts %}
  <script src="{% static 'stepshop/js/isotope.js' %}"></script>
{% endblock %}